### ISSUE TITLE
Geant4 macros are not being copied to install directory after `make install`

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/geant4lib#1]
I believe this is since the latest update to fix decay0 compilation issue rest-for-physics/framework#6

**Comment by nkx111** [comment]
In my case they are copied to `$REST_PATH/macros/geant4`. Isn't that the dir we want?

**Comment by jgalan** [comment]
Yes, thats ok, thats the dir we want. Well, I cannot reproduce the problem again.

**Comment by jgalan** [comment]
Plz, have a look to http://ezpc10.unizar.es/t/why-a-cmake-option-to-clear-install-target-before-installation/440
