### ISSUE TITLE
TRestGeant4Metadata TH1D energy spectrum does not recognize units

### ISSUE THREAD

**Issue by lobis** [rest-for-physics/geant4lib#26]
According to the documentation:

```
/// * **TH1D**: It will use a TH1D histogram from a ROOT file with a user
/// defined spectrum. It requires to define the parameters
/// `file="mySpectrum.root"` `spctName="histName"` and `range="(Ei,Ef)"`. The
/// ROOT file should contain a TH1D histogram with name `histName`. Only the
/// region of the spectrum inside the range `Ei-Ef` will be considered. The
/// energy units of the spectrum must be specified in the x-axis label of the
/// TH1D object. If no units are given in the x-label, the default units
/// considered will be keV. \code
///     // A TH1D input spectrum to produce underground muons in the range
///     between 150 and 400 GeV <energyDist type="TH1D" file="Muons.root"
///     spctName="LSCMuon" range="(150,400)" units="GeV" />
/// \endcode
```

But using `units` when selecting a TH1D as energy source does not seem to work, also I cannot find any reference to units in TH1D inside the source code so probably it was overlooked.

**Comment by jgalan** [comment]
No time to reproduce the problem now, but in principle, at `TRestGeant4Metadata` the `range` is being read considering the `GeV` units through the `Get2DVectorParameterWithUnits`.

```
source->SetEnergyRange(Get2DVectorParameterWithUnits("range", energyDefinition));
```

The TH1D energy spectrum is retrieved at `restG4.cc` level, and given to `PrimaryGeneratorAction`.

```
        // We set the initial spectrum energy provided from TH1D
        prim->SetSpectrum(&initialEnergySpectrum, minEnergy, maxEnergy);
```

It is at that method where the units of TH1D xlabel are interpreted, and re-scaled accordingly.

Do you find any problem at any of those two methods, `TRestGeant4Metadata` or `SetSpectrum`?

**Comment by jgalan** [comment]
When we read a physical energy parameter with REST, the value will be always stored in `keV`, as defined by the REST physics units system.

**Comment by jgalan** [comment]
It is not clear to me where is the problem, at which of those two methods there seems to be a problem?

**Comment by lobis** [comment]
> No time to reproduce the problem now, but in principle, at `TRestGeant4Metadata` the `range` is being read considering the `GeV` units through the `Get2DVectorParameterWithUnits`.

I had not set the range, only put "units", thought this should work (it doesn't), but could have made it work if I set put the range manually (I think it should work by only setting units, most of the time setting the range is redundant as you want the full range)

**Comment by jgalan** [comment]
"units" field behind a parameter is the units of the parameter, so the units of "range". Probably, you need to create a new parameter "th1d_units"? I dont understand what do you mean by redundant. It is just an option for the user to select the range...

**Comment by jgalan** [comment]
So, we could say "units" is a reserved "keyword"

**Comment by lobis** [comment]
> "units" field behind a parameter is the units of the parameter, so the units of "range". Probably, you need to create a new parameter "th1d_units"? I dont understand what do you mean by redundant. It is just an option for the user to select the range...

what I mean is that if you only want to select the units, it feels redundant to fill the range just for this pourpose (you need to open your histogram, see what the energy range was and put this information in the RML) when you probably want to sample the whole range anyway. Of course its good to have the option to select a range, but it shouldn't be a requierement to enable unit selection

**Comment by lobis** [comment]
> "units" field behind a parameter is the units of the parameter, so the units of "range". Probably, you need to create a new parameter "th1d_units"? I dont understand what do you mean by redundant. It is just an option for the user to select the range...

I think this is very confusing and probably nobody will be aware that you need to use a "th1d_units" instead of "units" for this particular case unless you are copy-pasting examples

**Comment by jgalan** [comment]
Well, the comment on the documentation is clear for me regarding the units of the TH1D. It needs to be defined at the x-label. You should not guess, you should read the doc.

**Comment by jgalan** [comment]
Of course, the "units" field following a parameter is always the units of the preceding parameter. This is a basic REST standard choice, there is no room for any other interpretation.

Still, the physics units documentation needs to be written.

https://rest-for-physics.github.io/rest-basics/physics-units.html

**Comment by lobis** [comment]
> Well, the comment on the documentation is clear for me regarding the units of the TH1D. It needs to be defined at the x-label. You should not guess, you should read the doc.
> 
> And I believe the behaviour is exactly as it is documented.

Yes you are right, I should not have tagged this as a bug, I didn't think of copying the `range` keyword from the documentation and thats why I thought it was a bug.

**Comment by jgalan** [comment]
So, in other words, the TH1D could have been built considering the x-axis in `MeV`, but the user could chose to define the `range` units in `GeV`.

**Comment by jgalan** [comment]
The user does not need to care about the units of TH1D as soon as the units are properly defined at the x-label.

**Comment by jgalan** [comment]
I let @nkx comment on it

**Comment by lobis** [comment]
> The user does not need to care about the units of TH1D as soon as the units are properly defined at the x-label.

True, at first its very unintuitive to me to extract the units from the axis label but I guess it makes sense, since you don't wanna change the units of a histogram once you have created it. The solution would've been to read better the documentation and not make assumptions. Thanks

**Comment by jgalan** [comment]
Yes, probably the trick of writing units on x-label is a bit hidden, but thats an issue that only concerns anyone generating the TH1D himself in other units different than keV.

**Comment by nkx111** [comment]
I think the "units" parameter can be used to define the units of x-axis if the label does not exist. By documentation we must construct the TH1D with proper x-label. If not, we can prompt a warning telling that the used unit is the one for "range" parameter.

**Comment by nkx111** [comment]
We don't need to modify restG4 to implement "units-parameter-for-x-axis" feature. I think we can just open the file and update the label of the contained TH1D object.
