### ISSUE TITLE
Problem defining active volumes when using GDML assembly

### ISSUE THREAD

**Issue by lobis** [rest-for-physics/geant4lib#4]
Active volumes are read from the RML in https://github.com/rest-for-physics/geant4lib/blob/master/src/TRestGeant4Metadata.cxx via `TGeoManager` GDML parser. The user is expected to insert the active volume names (e.g. "gas" which should correspond with an entry like `<physvol name="gas">` in the GDML), or, if none at inserted, all will be read from the `TGeoManager` and inserted into a set of strings.

This container of active volume names is later used in `restG4` (https://github.com/rest-for-physics/restG4/blob/master/src/DetectorConstruction.cc) where the Geant4 `G4VPhysicalVolume` is obtained via `GetPhysicalVolume((G4String)actVolName)` from the active volume name stored in the metadata.

When not using GDML assembly, the physical volume obtained via `GetPhysicalVolume` will have a name matching the one in the active volumes container constructed via `TGeoManager`. However, if this volumes are part of a GDML assembly, its name obtained via `TGeoNode::GetName()` (e.g. "gas") will not match the one of the physical volume (for example `av_6_impr_1_gasVolume_pv_0`) which is generated internally on the GDML and not visible in the .gdml file. If we could access this physical volume name via `TGeoManager` this could be fixed, but I have not found a way to do this, and I don't think its possible.

To add support for gdml assemblies (https://github.com/rest-for-physics/restG4/issues/3) we need to think of a different strategy.

My proposal is that since we only need to compare the active volume names with the Geant4 physical volume names in order to set the step sizes, that we do not use the active volume names but the logical volume names, which, in fact, is where the step size is defined in, its not defined in the physical volume as far as I am aware of. So in this case we should define the `maxStepSize` for the `"gasVolume"` which is the logical volume associated with the gas physical volume/s.

We would need to have logical volume names instead of physical volume names in the gdml, .i.e. `<activeVolume name="gasVolume" maxStepSize="0.1mm" />` instead of `<activeVolume name="gas" maxStepSize="0.1mm" />`. This makes more sense as if we currently have two `maxStepSize` declarations that reference the same logical volume, only the latest would have any effect.

**Comment by lobis** [comment]
Also, one problem is that right now the "sensitive volume" and "active volumes" are defined together (the sensitive volume is an active volume) however as I see it, the sensitive volume should be a physical volume while the active volumes should be logical volumes (or atleast the `maxStepSize` should be defined for logical volumes).

**Comment by jgalan** [comment]
One good thing of discourse is that I am able to quote text from your arguments, and comment. This seems not possible in GitHub. I believe this is more a discussion-like post.

**Comment by lobis** [comment]
> One good thing of discourse is that I am able to quote text from your arguments, and comment. This seems not possible in GitHub. I believe this is more a discussion-like post.

If you mean this, you can also quote here. I think it would be better to have the discussions here, since it will be easier to find in the future.

**Comment by jgalan** [comment]
> Active volumes are read from the RML in https://github.com/rest-for-physics/geant4lib/blob/master/src/TRestGeant4Metadata.cxx via `TGeoManager` GDML parser. The user is expected to insert the active volume names (e.g. "gas" which should correspond with an entry like `<physvol name="gas">` in the GDML), or, if none at inserted, all will be read from the `TGeoManager` and inserted into a set of strings.

Testing quote partial reply

**Comment by lobis** [comment]
I found relevant information in: https://geant4-userdoc.web.cern.ch/UsersGuides/ForApplicationDeveloper/html/Detector/Geometry/geomAssembly.html

**Comment by lobis** [comment]
For this change to work, the minimum C++ version needs to be 14.

**Comment by lobis** [comment]
This was solved by implementing a new class (details in https://github.com/rest-for-physics/geant4lib/pull/36) and improved in subsequent PRs
