### ISSUE TITLE
Crash when trying to retrieve the energy deposited at a given volume

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/geant4lib#72]
When launching the `TRestGeant4AnalysisProcess` with specific observables for volume energy deposition, the process will crash when calling the method `fOutputG4Event->GetEnergyDepositedInVolume(fVolumeID[n]);`  Line 531 at cxx.

The value of `fVolumeID[n]` is equal to 0. So I imagine that value is correct. Perhaps the problem is connected to a new way of handling volumes?

In particular it will crash when defining the following observable name:

```
<TRestGeant4AnalysisProcess name="g4Ana" ...>
    <observable name="gasVolumeEDep" />
</TRestGeant4AnalysisProcess>
```

This problem was reported by @glorialuzon .

In previous `geant4lib` code versions we had a method `TRestGeant4Event::AddTrack`. This method was responsible to add energy to the volumes that had been defined as active.

```
void TRestGeant4Event::AddTrack(TRestGeant4Track trk) {
    fTrack.push_back(trk);
    fNTracks = fTrack.size();
    fTotalDepositedEnergy += trk.GetTotalDepositedEnergy();
    for (int n = 0; n < GetNumberOfActiveVolumes(); n++)
        fVolumeDepositedEnergy[n] += trk.GetEnergyInVolume(n);
}
```

There was also a method that was initialising the elements of vector `fVolumeDepositedEnergy`. This was done be `restG4` invoking the following method (inside `DetectorConstructor` and `EventAction` in case of sub-events).

```
void TRestGeant4Event::AddActiveVolume(const string& volumeName) {
    fNVolumes++;
    fVolumeStored.push_back(1);
    fVolumeStoredNames.push_back(volumeName);
    fVolumeDepositedEnergy.push_back(0);
}
```

An option now would be to reimplement a method that does the calculation itself, or to come back to do the calculation at the time of production.

**Comment by jgalan** [comment]
@lobis could you have a look on how to fix this?

**Comment by lobis** [comment]
I will take a look into this, but we should write tests for validating these processes if they are important, it may be broken again in the future otherwise.

**Comment by jgalan** [comment]
I fully agree, it is just that testing implementation came much after the first developments.
