### ISSUE TITLE
Simplify ParticleSource, ParticleCollection and PrimaryGenerator

### ISSUE THREAD

**Issue by nkx111** [rest-for-physics/geant4lib#9]
It is very confusing that we have so many classes related to custom generator:

TRestGeant4ParticleSource: Storing particle information and particle distribution information
*It is a particle or a configuration?*
TRestGeant4ParticleCollection: Stores a list of loaded particles form generator file. Could also be inherited and connected to custom generator library(decay0)
*Why that "collection" could be custom generator?*
TRestGeant4PrimaryGenerator: Just keep the object of TRestGeant4ParticleSource and TRestGeant4ParticleCollection.
*It is named generator but does nothing*

I suggest to merge them altogether to have a clearer mind. We could **keep only TRestGeant4ParticleSource** and make it act as *configuration*. We leave a method `GetParticles()` to retrieve actual *particles* from the *configuration*

**Comment by jgalan** [comment]
Sure, I agree the present implementation is confusing. @lobis is also brainstorming to improve few parts of the code at geant4lib and restG4.

Perhaps we could organise an online meeting where we present the ideas for improvement, and then we discuss about to get a common perspective, then continue working offline?

**Comment by lobis** [comment]
I also agree with this, we could take a deep look into the G4ParticleSource and related clases to take inspiration.

**Comment by jgalan** [comment]
I have created a doodle to decide a date for the meeting.

https://doodle.com/poll/37ftvtaxhthucvi9?utm_source=poll&utm_medium=link

**Comment by nkx111** [comment]
I have created branch `revise_generators` in both geant4lib and restG4. I pushed my previous work on them which simplifies the class structure. It is compilable now. Maybe we can have a look before the meeting.

https://github.com/rest-for-physics/geant4lib/tree/revise_generators
https://github.com/rest-for-physics/restG4/tree/revise_generators

**Comment by jgalan** [comment]
Hi @nkx111 I believe these changes where already merged. Are we ready to close this issue?
